name: dataviz_python

channels:
  - default
  - conda-forge

dependencies:
  - python=3.8.*
  - pip
  - git
  - git-annex
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - nibabel
  - datalad=0.13
  - octave_kernel
  - texinfo

  - pip:
      - pybids==0.12.3 # to query bids datasets
      - datalad-installer
